<?php

/**
 * @file
 * Implements hook_theme().
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Element;

/**
 * Register template files.
 */
function reinfate_theme($existing, $type, $theme, $path) : array {
  return [
    'reinfate-page' => [
      'variables' => [
        'form' => NULL,
        'feedbacks_list' => NULL,
      ],
    ],
    'reinfate_feedback' => [
      'template' => 'reinfate-feedback',
      'render element' => 'elements',
      'title_suffix' => '',
      'content_attributes' => NULL,
    ],
    'reinfate_feedbacks_list' => [
      'template' => 'reinfate-feedbacks-list',
      'variables' => [
        'feedbacks' => NULL,
        'pager' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_reinfate_feedback(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var Feedback $entity */
  $entity = $variables['elements']['#reinfate_feedback'];
  $variables['label'] = $entity->label();
  $variables['url'] = $entity->toUrl()->toString();
  $variables['#attached']['library'][] = 'reinfate/feedback-style';
  $variables['attributes']['class'][] = Html::cleanCssIdentifier($entity->bundle());
  // Display default avatar if not uploaded.
  if (!isset($variables['content']['avatar']['#theme'])) {
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#style' => 'thumbnail',
      '#uri' => '/modules/custom/reinfate/assets/default-avatar.png',
      '#attributes' => [
        'alt' => 'avatar',
      ],
    ];
  }
}
